version: '3.8'

x-networks: &networks  # Define an anchor for environment variables
  networks:
    - sailtrace

services:

  wgb_be:
    image: wgb_be:latest
    env_file:
      - .env
    <<: *networks

  database:
    image: postgres
    container_name: wgb_db
    env_file:
      - .env
    ports:
      - 30001:5432
    volumes:
      - /waffengebraucht_suche/data/wgb_be/pg_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]
    <<: *networks

networks:
  wgb:
    external: true
