version: '3.8'

services:
  wgb_ui:
    image: wgb_ui:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./sites-enabled:/etc/nginx/sites-enabled:ro
    networks:
      wgb:

  wgb_be:
    image: wgb_be:latest
    env_file:
      - .env
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=warn"]
    networks:
      wgb:

  db:
    image: postgres


networks:
  wgb:
    external: true
